services:
  db:
    container_name: TelegramBotDB
    image: postgres:17.6
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
