spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/botdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  task:
    scheduling:
      enabled: true
      pool:
        size: 3
      thread-name-prefix: "scheduler-"
    execution:
      enabled: true
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 100
      thread-name-prefix: "async-"

telegram:
  bot:
    username: PLACEHOLDER
    token: PLACEHOLDER
    firstAdminId: PLACEHOLDER
    secondAdminId: PLACEHOLDER
