spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/botdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    username: PLACEHOLDER
    token: PLACEHOLDER
    firstAdminId: PLACEHOLDER
    secondAdminId: PLACEHOLDER
